# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

regulator_vibrator_mmi-y += moto_regulator_vibrator.o

obj-m += regulator_vibrator_mmi.o

