# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/synaptics_tcm_mmi_v2

ifneq ($(filter m y,$(USE_TOUCHSCREEN_MMI_I2C)),)
    obj-m += synaptics_i2c.o
    KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../../mmi_info/$(GKI_OBJ_MODULE_DIR)/Module.symvers
else
    obj-m += synaptics_spi.o
endif
