DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

ifeq ($(DLKM_INSTALL_TO_VENDOR_OUT),true)
ETS_FPS_MMI_MODULE_PATH := $(TARGET_OUT_VENDOR)/lib/modules/
else
ETS_FPS_MMI_MODULE_PATH := $(KERNEL_MODULES_OUT)
endif



ifeq ($(FPS_NAVI_ENABLE),true)
  ifneq ($(FPS_SLIDE_NAV),true)
	KERNEL_CFLAGS += CONFIG_INPUT_EGISTEC_FPS_NAVI=y
	KERNEL_CFLAGS += CONFIG_INPUT_EGISTEC_FPS_NAVI_HORIZON=y
	KERNEL_CFLAGS += CONFIG_INPUT_EGISTEC_FPS_NAVI_VERTICAL=y
  endif
endif

ifeq ($(EGIS_DISPLAY_SPEED_UP), true)
	KERNEL_CFLAGS += CONFIG_EGIS_DISPLAY_SPEED_UP=y
endif

ifeq ($(FPS_ENABLE_DOUBLE_TAP), true)
	KERNEL_CFLAGS += CONFIG_NAV_DOUBLE_TAP=y
endif

include $(CLEAR_VARS)
LOCAL_MODULE := ets_fps_mmi.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(ETS_FPS_MMI_MODULE_PATH)
KBUILD_OPTIONS_GKI += MODULE_KERNEL_VERSION=$(TARGET_KERNEL_VERSION)
include $(DLKM_DIR)/AndroidKernelModule.mk

