# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include \
		-I$(TOP)/motorola/kernel/modules/drivers/input/touchscreen/himax_v2_mmi
EXTRA_CFLAGS += -DCONFIG_TOUCHSCREEN_HIMAX_DEBUG \
		-DCONFIG_TOUCHSCREEN_HIMAX_INSPECT

EXTRA_CFLAGS += -DCONFIG_TOUCHSCREEN_HIMAX_INCELL
EXTRA_CFLAGS += -DCONFIG_HMX_DB

ifneq ($(filter hx83112,$(CONFIG_INPUT_HIMAX_V2_MMI_IC_NAME)),)
	EXTRA_CFLAGS += -D__HIMAX_HX83112_MOD__
endif

ifneq ($(filter hx83102,$(CONFIG_INPUT_HIMAX_V2_MMI_IC_NAME)),)
	EXTRA_CFLAGS += -D__HIMAX_HX83102_MOD__
endif

obj-m := himax_v2_mmi.o

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_HIMAX_V2_MMI_0FLASH)),)
	himax_v2_mmi-objs += himax_platform_QCT_SPI.o
	EXTRA_CFLAGS += -D__HIMAX_PLATFORM_SPI__ \
			-DHX_ZERO_FLASH
endif

himax_v2_mmi-objs += himax_common.o
himax_v2_mmi-objs += himax_debug.o
himax_v2_mmi-objs += himax_ic_incell_core.o
himax_v2_mmi-objs += himax_inspection.o
