obj-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_V3) := focaltech_v3.o
focaltech_v3-objs += focaltech_core.o
focaltech_v3-objs += focaltech_ex_fun.o
focaltech_v3-objs += focaltech_ex_mode.o
focaltech_v3-objs += focaltech_gesture.o
focaltech_v3-objs += focaltech_esdcheck.o
focaltech_v3-objs += focaltech_point_report_check.o
focaltech_v3-objs += focaltech_flash.o
focaltech_v3-objs += focaltech_flash/focaltech_upgrade_ft3681.o
focaltech_v3-objs += focaltech_spi.o
focaltech_v3-objs += focaltech_test/focaltech_test.o
focaltech_v3-objs += focaltech_test/focaltech_test_ini.o
focaltech_v3-objs += focaltech_test/supported_ic/focaltech_test_ft3681.o
focaltech_v3-objs += focaltech_ts_config.o

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
ccflags-y += -DCONFIG_INPUT_TOUCHSCREEN_MMI
focaltech_v3-objs += focaltech_ts_mmi.o
endif

ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_V3_MMI_NOISE_TEST_P2P) += -DCONFIG_FTS_NOISE_TEST_P2P
ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_V3_MMI_COMPATIBLE_WITH_GKI) += -DCONFIG_FTS_COMPATIBLE_WITH_GKI
ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_V3_MMI_DOUBLE_TAP_CONTROL) += -DCONFIG_FTS_DOUBLE_TAP_CONTROL
ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_V3_MMI_SUPPORT_HIGH_RESOLUTION) += -DCONFIG_FTS_SUPPORT_HIGH_RESOLUTION
ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_V3_MMI_VDD_GPIO_CONTROL) += -DCONFIG_FTS_VDD_GPIO_CONTROL
ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_V3_MMI_LAST_TIME) += -DCONFIG_FTS_LAST_TIME
ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_V3_MMI_ENABLE_DOUBLE_TAP) += -DFOCALTECH_SENSOR_EN
ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_V3_MMI_ENABLE_PALM) += -DFOCALTECH_PALM_SENSOR_EN
