# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include

cirrus_cs40l20-objs = cs40l20.o cs40l20-tables.o
obj-m += cirrus_cs40l20.o

