# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include \
		-I$(TOP)/motorola/kernel/modules/drivers/input/touchscreen/himax_mmi
EXTRA_CFLAGS += -DCONFIG_TOUCHSCREEN_HIMAX_DEBUG

ifeq ($(filter m y, $(CONFIG_TOUCHSCREEN_HIMAX_CHIPSET)),)
	obj-m := himax_mmi.o
endif

himax_mmi-objs += himax_platform.o
himax_mmi-objs += himax_ic.o
himax_mmi-objs += himax_common.o
himax_mmi-objs += himax_debug.o
