# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/ili9882_mmi \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/ili9882_mmi/firmware

ifeq ($(filter m y, $(CONFIG_TOUCHSCREEN_ILITEK_CHIPSET)),)
	obj-m += ili9882_mmi.o
endif

ifneq ($(filter m y,$(CONFIG_INPUT_ILI_0FLASH_MMI_ENABLE_DOUBLE_TAP)),)
	EXTRA_CFLAGS += -DILI_SENSOR_EN
	KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers
endif

ifneq ($(filter m y,$(CONFIG_INPUT_ILI_0FLASH_MMI_NOTIFY_TOUCH_STATE)),)
	EXTRA_CFLAGS += -DILI_SET_TOUCH_STATE
endif

ifneq ($(filter m y,$(CONFIG_INPUT_ILI_PANEL_NOTIFICATIONS)),)
EXTRA_CFLAGS += -DILI_CONFIG_PANEL_NOTIFICATIONS
endif
ifneq ($(filter m y,$(CONFIG_ILITEK_RESUME_BY_DDI)),)
EXTRA_CFLAGS += -DILI_CONFIG_RESUME_BY_DDI
endif
ifneq ($(filter m y,$(CONFIG_ILITEK_FW_PANEL)),)
EXTRA_CFLAGS += -DILI_FW_PANEL
endif
ifneq ($(filter m y,$(CONFIG_ILITEK_SUSPEND_PWROFF)),)
EXTRA_CFLAGS += -DILI_SUSPEND_PWROFF
endif
ifneq ($(filter m y,$(CONFIG_ILITEK_CHARGER)),)
EXTRA_CFLAGS += -DILI_CONFIG_CHARGER
endif
ifneq ($(filter m y,$(CONFIG_ILITEK_ESD)),)
EXTRA_CFLAGS += -DILI_CONFIG_ESD
endif
ifneq ($(filter m y,$(CONFIG_ILITEK_GESTURE)),)
EXTRA_CFLAGS += -DILI_CONFIG_GESTURE
endif

ifneq ($(filter m y,$(CONFIG_ILITEK_PANEL_GESTURE)),)
EXTRA_CFLAGS += -DILI_CONFIG_PANEL_GESTURE
endif

ifneq ($(filter m y,$(CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS)),)
    EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_EVENT_NOTIFICATIONS
endif

ili9882_mmi-objs += ili9882.o
ili9882_mmi-objs += ili9882_spi.o
ili9882_mmi-objs += ili9882_qcom.o
ili9882_mmi-objs += ili9882_ic.o
ili9882_mmi-objs += ili9882_touch.o
ili9882_mmi-objs += ili9882_mp.o
ili9882_mmi-objs += ili9882_hostdl.o
ili9882_mmi-objs += ili9882_node.o
ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
    KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../touchscreen_mmi/$(GKI_OBJ_MODULE_DIR)/Module.symvers
    EXTRA_CFLAGS += -DCONFIG_INPUT_TOUCHSCREEN_MMI
    ili9882_mmi-objs += ili_mmi_class.o
endif
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/../../kernel/msm-$(MODULE_KERNEL_VERSION)/Module.symvers
