# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include \
		-I$(TOP)/motorola/kernel/modules/drivers/power/mmi_parallel_charger_qc3p

obj-m += mmi_parallel_charger_qc3p.o
mmi_parallel_charger_qc3p-objs += mmi_charger_class.o
mmi_parallel_charger_qc3p-objs += mmi_charger_core.o
mmi_parallel_charger_qc3p-objs += mmi_charger_pump_policy.o
mmi_parallel_charger_qc3p-objs += bq2597x_charger.o
mmi_parallel_charger_qc3p-objs += qpnp_pmic_charger.o

#ifeq ($(CONFIG_MMI_PL_CP_POLICY), y)
#endif
