# add -Wall to try to catch everything we canss
# EXTRA_CFLAGS += -Wallss
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/stmicro_mmi

obj-m := stmicro_mmi.o
stmicro_mmi-objs := fts.o fts_proc.o
stmicro_mmi-objs += fts_lib/ftsCompensation.o
stmicro_mmi-objs += fts_lib/ftsCore.o
stmicro_mmi-objs += fts_lib/ftsError.o
stmicro_mmi-objs += fts_lib/ftsFlash.o
stmicro_mmi-objs += fts_lib/ftsFrame.o
stmicro_mmi-objs += fts_lib/ftsGesture.o
stmicro_mmi-objs += fts_lib/ftsIO.o
stmicro_mmi-objs += fts_lib/ftsTest.o
stmicro_mmi-objs += fts_lib/ftsTime.o
stmicro_mmi-objs += fts_lib/ftsTool.o

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
    EXTRA_CFLAGS += -DCONFIG_INPUT_TOUCHSCREEN_MMI
    stmicro_mmi-objs += fts_mmi_class.o
endif

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../touchscreen_mmi/Module.symvers
