KERNEL_DIR_PATH = $(shell find $(TOP)/kernel/ -name "msm-*" | head -1)

KERNEL_VERSION_NAME = $(shell basename $(KERNEL_DIR_PATH))

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include

ifneq (,$(filter river%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter doha%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter sofia%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter odin%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL \
		-DCONFIG_CAPSENSE_ATTACH_CAL
endif

ifneq (,$(filter olson%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL \
		-DCONFIG_CAPSENSE_FLIP_CAL
endif

ifneq (,$(filter rav%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter burton%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

EXTRA_CFLAGS += -I$(TOP)/kernel/$(KERNEL_VERSION_NAME)/drivers/base
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../sensors/Module.symvers

sx932x_sar-y := sx933x_sar.o

obj-m += sx933x_sar.o
