# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include

mmi_info-objs += mmi_soc_info.o
mmi_info-objs += mmi_storage_info.o
mmi_info-objs += mmi_ram_info.o
mmi_info-objs += mmi_unit_info.o
mmi_info-objs += mmi_boot_info.o
mmi_info-objs += mmi_info_main.o
obj-m += mmi_info.o