ccflags-y += -I$(srctree)/drivers/input/touchscreen/focaltech_0flash_v2_mmi/include

obj-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_0FLASH_V2_MMI) := focaltech_0flash_v2_mmi.o
focaltech_0flash_v2_mmi-objs += focaltech_core.o
focaltech_0flash_v2_mmi-objs += focaltech_esdcheck.o
focaltech_0flash_v2_mmi-objs += focaltech_ex_fun.o
focaltech_0flash_v2_mmi-objs += focaltech_ex_mode.o
focaltech_0flash_v2_mmi-objs += focaltech_flash.o
focaltech_0flash_v2_mmi-objs += focaltech_gesture.o
focaltech_0flash_v2_mmi-objs += focaltech_point_report_check.o
focaltech_0flash_v2_mmi-objs += focaltech_spi.o

ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_0FLASH_V2_MMI_ENABLE_DOUBLE_TAP) += -DFOCALTECH_SENSOR_EN
ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_0FLASH_V2_MMI_NOTIFY_TOUCH_STATE) += -DFTS_SET_TOUCH_STATE
ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_0FLASH_V2_MMI_ESD_EN) += -DFOCALTECH_ESD_EN
ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_0FLASH_V2_MMI_PANEL_NOTIFICATIONS) += -DFOCALTECH_CONFIG_PANEL_NOTIFICATIONS
ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_0FLASH_V2_MMI_DEBUG_EN) += -DFOCALTECH_DEBUG_EN

ifneq ($(filter ft8057,$(CONFIG_INPUT_FOCALTECH_0FLASH_MMI_IC_NAME)),)
ccflags-y += -DCONFIG_INPUT_FOCALTECH_0FLASH_MMI_IC_NAME_FT8057
else
ccflags-y += -DCONFIG_INPUT_FOCALTECH_0FLASH_MMI_IC_NAME_FT8726
endif

ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_0FLASH_V2_MMI_PINCTRL_EN) += -DFOCALTECH_PINCTRL_EN
ccflags-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_0FLASH_V2_MMI_LAST_TIME) += -DFTS_LAST_TIME_EN
