# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include

ldc2114_keys-objs := ldc2114.o ldc2114-debugfs.o

ifeq ($(TARGET_BUILD_VARIANT),userdebug)
    # Following line is in control of extra debug
    EXTRA_CFLAGS += -DLDC2114_POLL_DEBUG -DLDC2114_CFG_DEBUG
endif

obj-m = ldc2114_keys.o
