# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/mmi_charger

ifneq ($(filter m y,$(CONFIG_WIRELESS_CPS4035B)),)
	EXTRA_CFLAGS += -DWIRELESS_CPS4035B
endif

ifneq ($(filter m y,$(CONFIG_WIRELESS_CPS4019)),)
	EXTRA_CFLAGS += -DWIRELESS_CPS4019
endif

obj-m += qti_glink_charger.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../bm_adsp_ulog/$(GKI_OBJ_MODULE_DIR)/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../mmi_charger/$(GKI_OBJ_MODULE_DIR)/Module.symvers
