obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/

obj-$(CONFIG_P938X_CHARGER)	+= p938x_charger/
obj-$(CONFIG_QPNP_ADAPTIVE_CHARGE) += qpnp_adaptive_charge/
obj-$(CONFIG_QPNP_SMBCHARGER_MMI) += qpnp-smbcharger-mmi/
obj-$(CONFIG_MMI_PARALLEL_CHARGER) += mmi_parallel_charger/
obj-$(CONFIG_MMI_PARALLEL_CHARGER_QC3P) += mmi_parallel_charger_qc3p/
obj-$(CONFIG_BQ2597X_MMI) += bq2597x_mmi/
