# add -Wall to try to catch everything we can.
# EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += \
		-I$(TOP)/motorola/kernel/modules/include \
		-I$(TOP)/motorola/kernel/modules/drivers/input/touchscreen/sec_mmi

ifneq (,$(filter racer% burton%,$(TARGET_PRODUCT)))
# NOTE: USE_STUBS option will go away when touchscreen_mmi class introduced, but
#       CONFIG_DRM_DYNAMIC_REFRESH_RATE is staying!!!
EXTRA_CFLAGS += -DUSE_STUBS -DCONFIG_DRM_DYNAMIC_REFRESH_RATE
endif

obj-m := sec_mmi.o
sec_mmi-objs = sec_ts.o sec_ts_fn.o sec_ts_fw.o sec_ts_mmi.o sec_cmd.o sec_ts_only_vendor.o
