DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := sc760x_charger_mmi.ko

LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
LOCAL_ADDITIONAL_DEPENDENCIES := $(KERNEL_MODULES_OUT)/mmi_charger.ko

ifeq ($(THERMAL_RATIO_CONTROL),true)
	KERNEL_CFLAGS += CONFIG_THERMAL_RATIO_CONTROL=y
	KBUILD_OPTIONS += CONFIG_THERMAL_RATIO_CONTROL=y
endif
KBUILD_OPTIONS_GKI += GKI_OBJ_MODULE_DIR=gki
include $(DLKM_DIR)/AndroidKernelModule.mk
