# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include

prod_list := hawao penang pnangn fogona
find_target := $(foreach find, $(prod_list), $(findstring $(find), $(TARGET_PRODUCT)))
find_target := $(strip $(find_target))
$(warning find_target=$(find_target))
ifneq ($(find_target),)
$(warning define SUPPORT_POWER_GPIO)
EXTRA_CFLAGS += -DSUPPORT_POWER_GPIO
endif

obj-m := fpsensor_spi_tee_v1.o
fpsensor_spi_tee_v1-objs := \
	fpsensor_spi_tee.o
