# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include

prod_list := devon
find_target := $(foreach find, $(prod_list), $(findstring $(find), $(TARGET_PRODUCT)))
find_target := $(strip $(find_target))
$(warning find_target=$(find_target))
ifeq ($(find_target),y)
$(warning define SUPPORT_PIN_CTRL)
EXTRA_CFLAGS += -DSUPPORT_PIN_CTRL
endif

ifneq ($(filter m y,$(CONFIG_INPUT_MISC_FPC1020_SAVE_TO_CLASS_DEVICE)),)
	EXTRA_CFLAGS += -DCONFIG_INPUT_MISC_FPC1020_SAVE_TO_CLASS_DEVICE
endif

fpc1020_mmi-y += fpc1020_tee.o

obj-m += fpc1020_mmi.o

