# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

ifneq ($(filter banks%, $(TARGET_PRODUCT)),)
	EXTRA_CFLAGS += -DSOFTDEP_GPIO_PCAL6408
endif

obj-m += sr100.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../mmi_info/Module.symvers
