# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include
EXTRA_CFLAGS += -DCONFIG_MADERA_IRQ_CS47L90

cirrus_irq-madera-objs = irq-madera.o irq-madera-cs47l90.o

obj-m += cirrus_irq-madera.o
