# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include -I$(TOP)/motorola/kernel/modules/drivers/input/misc

ldc2114_keys-objs := ldc2114.o

ifeq ($(TARGET_BUILD_VARIANT),userdebug)
    EXTRA_CFLAGS += -DLDC2114_CHARDEV
    ldc2114_keys-objs += ldc2114-cdev.o
endif

obj-m = ldc2114_keys.o
