DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

KBUILD_OPTIONS += CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5=y

KBUILD_OPTIONS += CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_DEVICETREE_SUPPORT=y

ifeq ($(TOUCHSCREEN_CYPRESS_CYTTSP5_I2C),true)
    KBUILD_OPTIONS += CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_I2C=y
endif

ifeq ($(TOUCHSCREEN_CYPRESS_CYTTSP5_SPI),true)
    KBUILD_OPTIONS += CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_SPI=y
endif


ifeq ($(TOUCHSCREEN_CYPRESS_CYTTSP5_MT_A),true)
    KBUILD_OPTIONS += CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_MT_A=y
endif

ifeq ($(TOUCHSCREEN_CYPRESS_CYTTSP5_MT_B),true)
    KBUILD_OPTIONS += CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_MT_B=y
endif

ifeq ($(TOUCHSCREEN_CYPRESS_CYTTSP5_BUTTON),true)
    KBUILD_OPTIONS += CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_BUTTON=y
endif

ifeq ($(TOUCHSCREEN_CYPRESS_CYTTSP5_PROXIMITY),true)
    KBUILD_OPTIONS += CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_PROXIMITY=y
endif


include $(CLEAR_VARS)
LOCAL_MODULE := parade_tma5xx_mmi_core.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
include $(DLKM_DIR)/AndroidKernelModule.mk

include $(CLEAR_VARS)
LOCAL_MODULE := parade_tma5xx_mmi_loader.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
include $(DLKM_DIR)/AndroidKernelModule.mk

include $(CLEAR_VARS)
LOCAL_MODULE := parade_tma5xx_mmi_debug.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
include $(DLKM_DIR)/AndroidKernelModule.mk

include $(CLEAR_VARS)
LOCAL_MODULE := parade_tma5xx_mmi_access.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
KBUILD_OPTIONS += CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_DEVICE_ACCESS_API=y
include $(DLKM_DIR)/AndroidKernelModule.mk

KBUILD_OPTIONS_GKI += GKI_OBJ_MODULE_DIR=gki
