###
# Copyright (C) 2018 Fourier Semiconductor Inc. All rights reserved.
#

# FS16XX VERSION INFO, DON'T REMOVE THIS LINE!!!
snd-soc-fs16xx-objs := fs16xx.o
snd-soc-fs16xx-objs += fs16xx_preset.o
snd-soc-fs16xx-objs += fs16xx_calibration.o
obj-$(CONFIG_SND_SOC_FS16XX) += snd-soc-fs16xx.o
