# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -DCONFIG_PM_WAKELOCKS
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \

ifneq ($(filter m y,$(CONFIG_MMI_RELAY)),)
	EXTRA_CFLAGS += -DMMI_RELAY_MODULE
endif

anc_fps_mmi-y += jiiov_platform.o jiiov_netlink.o custom.o

obj-m += anc_fps_mmi.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../mmi_relay/$(GKI_OBJ_MODULE_DIR)/Module.symvers
