# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/sgm4154x_chg_mmi

ifneq ($(filter m y,$(CONFIG_MMI_QC3P_TURBO_CHARGER)),)
        EXTRA_CFLAGS += -DCONFIG_MMI_QC3P_TURBO_CHARGER
endif

ifneq ($(filter m y,$(CONFIG_MMI_HAWAO_VBUS_SAMPLE_RATIO)),)
        EXTRA_CFLAGS += -DCONFIG_MMI_HAWAO_VBUS_SAMPLE_RATIO
endif

obj-m += sgm4154x_charger.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../mmi_discrete_charger/$(GKI_OBJ_MODULE_DIR)/Module.symvers
