# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include
ifeq ($(CONFIG_ARCH_SDM450), y)
EXTRA_CFLAGS += -DCONFIG_MFD_CS47L35
cirrus_madera-core-objs = madera-core.o madera-spi.o madera-core.o madera-spi.o cs47l35-tables.o
else
EXTRA_CFLAGS += -DCONFIG_MFD_CS47L90
cirrus_madera-core-objs = madera-core.o madera-spi.o madera-core.o madera-spi.o cs47l90-tables.o
endif

obj-m += cirrus_madera-core.o
