# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/bq2589x_chg_mmi

obj-m += bq2589x_charger.o

ifneq ($(filter m y,$(CONFIG_MMI_QC3P_TURBO_CHARGER)),)
        EXTRA_CFLAGS += -DCONFIG_MMI_QC3P_TURBO_CHARGER
endif

ifneq ($(filter m y,$(CONFIG_MMI_QC3P_WT6670_DETECTED)),)
        EXTRA_CFLAGS += -DCONFIG_MMI_QC3P_WT6670_DETECTED
endif

ifneq ($(filter m y,$(CONFIG_MMI_EXT_CHG_LED)),)
        EXTRA_CFLAGS += -DCONFIG_MMI_EXT_CHG_LED
endif

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../mmi_discrete_charger/$(GKI_OBJ_MODULE_DIR)/Module.symvers
