# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

ldo_vibrator_mmi-y += moto_ldo_vibrator.o

obj-m += ldo_vibrator_mmi.o

