#
# Makefile for the vl53L0 drivers.
#

# Each configuration option enables a list of files.

EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/drivers/input/misc/vl53L0
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/drivers/input/misc/vl53L0/inc

obj-m          += stmvl53l0.o
stmvl53l0-objs := stmvl53l0_module.o stmvl53l0_module-i2c.o
stmvl53l0-objs += src/vl53l0_api_calibration.o src/vl53l0_api_core.o
stmvl53l0-objs += src/vl53l0_api_histogram.o src/vl53l0_api_ranging.o
stmvl53l0-objs += src/vl53l0_api_strings.o src/vl53l0_api.o src/vl53l0_platform.o
stmvl53l0-objs += src/vl53l0_i2c_platform.o src/vl53l0_port_i2c.o
