# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += \
		-I$(TOP)/motorola/kernel/modules/include \
		-I$(TOP)/motorola/kernel/modules/drivers/input/touchscreen/goodix_berlin_mmi

obj-m := goodix_brl_mmi.o
goodix_brl_mmi-objs = goodix_brl_fwupdate.o goodix_brl_hw.o goodix_brl_i2c.o goodix_cfg_bin.o goodix_ts_core.o goodix_ts_utils.o

obj-m += goodix_brl_tools_mmi.o
goodix_brl_tools_mmi-objs = goodix_ts_tools.o

obj-m += goodix_brl_gesture_mmi.o
goodix_brl_gesture_mmi-objs = goodix_ts_gesture.o

