# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

obj-m := goodix_brl_mmi.o
goodix_brl_mmi-objs := \
					goodix_brl_i2c.o \
					goodix_brl_spi.o \
					goodix_ts_core.o \
					goodix_brl_hw.o \
					goodix_cfg_bin.o \
					goodix_ts_utils.o \
					goodix_brl_fwupdate.o \
					goodix_ts_inspect.o \
					goodix_ts_tools.o \
					goodix_ts_config.o

ifneq ($(filter m y, $(CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_EVENT_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_DRM_PANEL_NOTIFICATIONS)),)
    EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_TOUCHSCREEN_GOODIX_BRL_SPI)),)
    EXTRA_CFLAGS += -DCONFIG_TOUCHSCREEN_GOODIX_BRL_SPI
endif

ifneq ($(filter m y,$(CONFIG_GTP_FOD)),)
    EXTRA_CFLAGS += -DCONFIG_GTP_FOD
    goodix_brl_mmi-objs += goodix_ts_gesture_fod.o
else
    goodix_brl_mmi-objs += goodix_ts_gesture.o
endif

ifneq ($(filter m y,$(CONFIG_GTP_LIMIT_USE_SUPPLIER)),)
    EXTRA_CFLAGS += -DCONFIG_GTP_LIMIT_USE_SUPPLIER
endif

ifneq ($(filter m y,$(CONFIG_GTP_ENABLE_PM_QOS)),)
    EXTRA_CFLAGS += -DCONFIG_GTP_ENABLE_PM_QOS
endif

ifneq ($(filter m y,$(CONFIG_GOODIX_ESD_ENABLE)),)
    EXTRA_CFLAGS += -DCONFIG_GOODIX_ESD_ENABLE
endif

ifneq ($(filter m y,$(CONFIG_TARGET_BUILD_FACROTY)),)
    EXTRA_CFLAGS += -DGTP_SAVE_IN_CSV
endif

ifneq ($(filter m y,$(CONFIG_GTP_LAST_TIME)),)
    EXTRA_CFLAGS += -DCONFIG_GTP_LAST_TIME
endif

ifneq ($(filter m y,$(CONFIG_GTP_DDA_STYLUS)),)
    EXTRA_CFLAGS += -DCONFIG_GTP_DDA_STYLUS
    goodix_brl_mmi-objs += goodix_ts_dda.o
endif

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
    EXTRA_CFLAGS += -DCONFIG_INPUT_TOUCHSCREEN_MMI
    goodix_brl_mmi-objs += goodix_ts_mmi.o
endif

ifneq ($(findstring _factory,$(TARGET_PRODUCT)),)
USE_TARGET_PRODUCT := $(strip $(subst _factory,, $(TARGET_PRODUCT)))
else
USE_TARGET_PRODUCT := $(TARGET_PRODUCT)
endif

ifneq ($(filter oneli, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_ONELI
else ifneq ($(filter hiphi, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_HIPHI
else ifneq ($(filter hiphic, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_HIPHIC
else ifneq ($(filter li, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_LI
else ifneq ($(filter eqs, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_EQS
else ifneq ($(filter tundra%, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_TUNDRA
else ifneq ($(filter miami%, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_MIAMI
endif
$(warning "william EXTRA_CFLAGS = $(EXTRA_CFLAGS)")

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../touchscreen_mmi/$(GKI_OBJ_MODULE_DIR)/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../mmi_info/$(GKI_OBJ_MODULE_DIR)/Module.symvers
