ccflags-y += -I$(srctree)/drivers/base

ccflags-$(CONFIG_AW9610X_POWER_SUPPLY_ONLINE) += -DCONFIG_USE_POWER_SUPPLY_ONLINE

obj-$(CONFIG_AW9610X_SAR) := aw9610x.o
aw9610x-objs += aw9610x_sar.o
aw9610x-objs += aw_bin_parse.o
