# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/goodix_berlin_mmi/include

ifneq ($(filter m y,$(CONFIG_USE_TOUCHSCREEN_MMI_I2C)),)
	obj-m = goodix_brl_i2c.o
else
	obj-m = goodix_brl_spi.o
endif
