# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/usb/typec/mmi_tcpc

subdir-ccflags-y += -Wall -Werror -DCONFIG_RT_REGMAP

EXTRA_CFLAGS += -DCONFIG_PD_DBG_INFO

ifneq ($(filter m y,$(CONFIG_TCPC_CLASS)),)
	EXTRA_CFLAGS += -DCONFIG_TCPC_CLASS
endif

ifneq ($(filter m y,$(CONFIG_USB_POWER_DELIVERY)),)
	EXTRA_CFLAGS += -DCONFIG_USB_POWER_DELIVERY
endif

ifneq ($(filter m y,$(CONFIG_TCPC_RT1711H)),)
	obj-m	+= tcpc_rt1711h.o
endif

ifneq ($(filter m y,$(CONFIG_TCPC_SGM7220)),)
	obj-m	+= tcpc_sgm7220.o
endif

ifneq ($(filter m y,$(CONFIG_TCPC_DEVON_POLLING_TIME)),)
        EXTRA_CFLAGS += -DCONFIG_TCPC_DEVON_POLLING_TIME
endif

tcpc_class-objs			+= tcpci_core.o tcpci_typec.o tcpci_timer.o \
		tcpm.o tcpci.o pd_dbg_info.o tcpci_alert.o rt-regmap.o tcpci_dual_role.o

ifneq ($(filter m y,$(CONFIG_USB_POWER_DELIVERY)),)
tcpc_class-objs			+= tcpci_event.o \
		pd_core.o pd_policy_engine.o pd_process_evt.o \
		pd_dpm_core.o pd_dpm_uvdm.o pd_dpm_alt_mode_dp.o pd_dpm_pdo_select.o\
		pd_dpm_reaction.o \
		pd_process_evt_snk.o pd_process_evt_src.o pd_process_evt_vdm.o \
		pd_process_evt_drs.o pd_process_evt_prs.o pd_process_evt_vcs.o \
		pd_process_evt_dbg.o pd_process_evt_tcp.o pd_process_evt_com.o \
		pd_policy_engine_src.o pd_policy_engine_snk.o pd_policy_engine_ufp.o pd_policy_engine_vcs.o \
		pd_policy_engine_dfp.o pd_policy_engine_dr.o pd_policy_engine_drs.o pd_policy_engine_prs.o \
		pd_policy_engine_dbg.o pd_policy_engine_com.o pd_dpm_alt_mode_dc.o pd_adapter.o \
		pd_dpm_mmi_adapter.o
endif

obj-m	+= tcpc_class.o
obj-m	+= rt_pd_manager.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../adapter_class/$(GKI_OBJ_MODULE_DIR)/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../power/mmi_discrete_charger/$(GKI_OBJ_MODULE_DIR)/Module.symvers
