subdir-ccflags-y += -Wall -Werror -DCONFIG_RT_REGMAP

ccflags-y += -DCONFIG_PD_DBG_INFO

ifneq ($(filter m y,$(CONFIG_TCPC_CLASS)),)
ccflags-y += -DCONFIG_TCPC_CLASS
endif

ccflags-$(CONFIG_USB_POWER_DELIVERY) += -DCONFIG_USB_POWER_DELIVERY

obj-$(CONFIG_TCPC_RT1711H)	+= tcpc_rt1711h.o

obj-$(CONFIG_TCPC_SGM7220)	+= tcpc_sgm7220.o

tcpc_class-objs			+= tcpci_core.o tcpci_typec.o tcpci_timer.o \
		tcpm.o tcpci.o pd_dbg_info.o tcpci_alert.o rt-regmap.o tcpci_dual_role.o

ifneq ($(filter m y,$(CONFIG_USB_POWER_DELIVERY)),)
tcpc_class-objs			+= tcpci_event.o \
		pd_core.o pd_policy_engine.o pd_process_evt.o \
		pd_dpm_core.o pd_dpm_uvdm.o pd_dpm_alt_mode_dp.o pd_dpm_pdo_select.o\
		pd_dpm_reaction.o \
		pd_process_evt_snk.o pd_process_evt_src.o pd_process_evt_vdm.o \
		pd_process_evt_drs.o pd_process_evt_prs.o pd_process_evt_vcs.o \
		pd_process_evt_dbg.o pd_process_evt_tcp.o pd_process_evt_com.o \
		pd_policy_engine_src.o pd_policy_engine_snk.o pd_policy_engine_ufp.o pd_policy_engine_vcs.o \
		pd_policy_engine_dfp.o pd_policy_engine_dr.o pd_policy_engine_drs.o pd_policy_engine_prs.o \
		pd_policy_engine_dbg.o pd_policy_engine_com.o pd_dpm_alt_mode_dc.o pd_adapter.o
endif

obj-$(CONFIG_TCPC_CLASS)	+= tcpc_class.o
obj-$(CONFIG_RT_PD_MANAGER)	+= rt_pd_manager.o
