# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/chipone_tddi_fhd_mmi
ifneq ($(filter m y,$(CONFIG_CHIPONE_ESD)),)
EXTRA_CFLAGS += -DCONFIG_CTS_ESD_PROTECTION
endif

#EXTRA_CFLAGS += -DCONFIG_CTS_I2C_HOST

ifneq ($(filter m y,$(CONFIG_INPUT_CHIPONE_0FLASH_MMI_ENABLE_DOUBLE_TAP)),)
	EXTRA_CFLAGS += -DCHIPONE_SENSOR_EN
	KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers
endif

ifneq ($(filter m y,$(CONFIG_INPUT_CHIPONE_0FLASH_MMI_NOTIFY_TOUCH_STATE)),)
	EXTRA_CFLAGS += -DCHIPONE_SET_TOUCH_STATE
endif

ifneq ($(filter m y,$(CONFIG_INPUT_CHIPONE_PANEL_NOTIFICATIONS)),)
EXTRA_CFLAGS += -DCHIPONE_CONFIG_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_GTP_LAST_TIME)),)
	EXTRA_CFLAGS += -DCONFIG_GTP_LAST_TIME
endif

ifneq ($(filter m y, $(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	EXTRA_CFLAGS += -DCONFIG_BOARD_USES_DOUBLE_TAP_CTRL
endif

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
	EXTRA_CFLAGS += -DCONFIG_INPUT_TOUCHSCREEN_MMI
endif

ifeq ($(TARGET_BUILD_VARIANT),user)
	EXTRA_CFLAGS += -DCFG_CTS_FOR_GKI
endif

ifneq ($(filter m y,$(TOUCHSCREEN_PM_BRL_SPI)),)
	EXTRA_CFLAGS += -DTOUCHSCREEN_PM_BRL_SPI
endif

#obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += chipone-tddi.o
obj-m += chipone_tddi_v2_mmi.o

chipone_tddi_v2_mmi-objs := cts_driver.o
chipone_tddi_v2_mmi-objs += cts_core.o
chipone_tddi_v2_mmi-objs += cts_sfctrlv2.o
chipone_tddi_v2_mmi-objs += cts_spi_flash.o
chipone_tddi_v2_mmi-objs += cts_firmware.o
chipone_tddi_v2_mmi-objs += cts_test.o
chipone_tddi_v2_mmi-objs += cts_charger_detect.o
chipone_tddi_v2_mmi-objs += cts_earjack_detect.o
chipone_tddi_v2_mmi-objs += cts_tcs.o
chipone_tddi_v2_mmi-objs += cts_platform.o
chipone_tddi_v2_mmi-objs += cts_tool.o
chipone_tddi_v2_mmi-objs += cts_sysfs.o
chipone_tddi_v2_mmi-objs += cts_strerror.o
chipone_tddi_v2_mmi-objs += cts_oem.o
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../touchscreen_mmi/$(GKI_OBJ_MODULE_DIR)/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../mmi_info/$(GKI_OBJ_MODULE_DIR)/Module.symvers
