ccflags-$(CONFIG_TOUCHCLASS_MMI_GESTURE_POISON_EVENT) += -DTS_MMI_TOUCH_GESTURE_POISON_EVENT
ccflags-$(CONFIG_TOUCHCLASS_MMI_MULTIWAY_UPDATE_FW) += -DTS_MMI_TOUCH_MULTIWAY_UPDATE_FW

obj-$(CONFIG_INPUT_TOUCHSCREEN_MMI) := touchscreen_mmi.o
touchscreen_mmi-objs := touchscreen_mmi_class.o touchscreen_mmi_panel.o touchscreen_mmi_notif.o touchscreen_mmi_gesture.o
