obj-$(CONFIG_MMI_DISCRETE_TURBO_CHARGER) += mmi_discrete_turbo_charger.o
mmi_discrete_turbo_charger-objs += mmi_charger_class.o
mmi_discrete_turbo_charger-objs += mmi_charger_core.o
mmi_discrete_turbo_charger-objs += mmi_charger_pump_policy.o
mmi_discrete_turbo_charger-objs += mmi_cp_charger.o
mmi_discrete_turbo_charger-objs += qpnp_pmic_charger.o
mmi_discrete_turbo_charger-objs += mmi_qc3p.o
mmi_discrete_turbo_charger-objs += mmi_qc3p_cp_policy.o
