DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := rbs_fod_mmi.ko
LOCAL_MODULE_TAGS := optional
ifeq ($(DLKM_INSTALL_TO_VENDOR_OUT),true)
ETS_FPS_MMI_MODULE_PATH := $(TARGET_OUT_VENDOR)/lib/modules/
else
ETS_FPS_MMI_MODULE_PATH := $(KERNEL_MODULES_OUT)
endif
LOCAL_MODULE_PATH := $(ETS_FPS_MMI_MODULE_PATH)


ifeq ($(EGIS_FPS_PANEL_NOTIFICATIONS),true)
    KERNEL_CFLAGS += CONFIG_EGIS_PANEL_NOTIFICATIONS=y
endif


KERNEL_CFLAGS += CONFIG_MMI_RELAY=y

LOCAL_ADDITIONAL_DEPENDENCIES := $(KERNEL_MODULES_OUT)/mmi_relay.ko
KBUILD_OPTIONS_GKI += GKI_OBJ_MODULE_DIR=gki
include $(DLKM_DIR)/AndroidKernelModule.mk

